In [1]:
import tensorflow as tf

In [5]:
a = tf.constant([[1, 2],[3,4]])
print('Type: ', a.dtype)
print('Rank: ', tf.rank(a))
print('Dims: ', a.ndim)
print('Shape: ', a.shape)

Type:  <dtype: 'int32'>
Rank:  tf.Tensor(2, shape=(), dtype=int32)
Dims:  2
Shape:  (2, 2)


## Change Type

In [9]:
a =tf.cast(a,dtype=tf.float32)
print('Type: ', a.dtype)
print(a)


Type:  <dtype: 'float32'>
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


## Indexing

In [10]:
# Notice these all return tensors
print(a[0])
print(a[0][0])
print(a[0,0])

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [12]:
print(a[0][0].numpy()) # use numpy() method to extract values

1.0


## Arg Min / Max

In [19]:
tf.argmin(a[0]), tf.argmax(a[0])

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>)

## Expanding Dimensions

In [15]:
print(tf.expand_dims(a,axis=0).shape)
print(tf.expand_dims(a,axis=1).shape)
print(tf.expand_dims(a,axis=2).shape)
print(tf.expand_dims(a,axis=-1).shape)


(1, 2, 2)
(2, 1, 2)
(2, 2, 1)
(2, 2, 1)


## Reshaping Tensors

In [20]:
a = tf.constant([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
a.shape # 3x4 Matrix

TensorShape([3, 4])

In [21]:
a = tf.reshape(a, shape=(2, 2, 3))
a.shape

TensorShape([2, 2, 3])

In [22]:
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [24]:
a = tf.reshape(a, shape=(12,)) # one way to flatten the array
a.shape

TensorShape([12])

In [25]:
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>